# Generated by Django 4.2.4 on 2023-09-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceSphereBackEnd', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
