# Generated by Django 4.2.5 on 2023-09-06 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serviceSphereBackEnd', '0003_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('suburb', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceSphereBackEnd.country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceSphereBackEnd.province')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceSphereBackEnd.address'),
        ),
    ]
